services:
  db:
    image: mysql:9.1.0
    container_name: db
    volumes:
      # persist to host instead of data container volume
      #- ./.mysql/db_data:/var/lib/mysql
      - db_data:/var/lib/mysql
      - ./.mysql/db-init.sql:/docker-entrypoint-initdb.d/db-init.sql
      - ./.mysql/my.cnf:/etc/mysql/conf.d/my.cnf:ro
    hostname: db
    ports:
      - "0.0.0.0:3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_ROOT_HOST=%
  
volumes:
  db_data: